language: python
dist: xenial
python:
- '3.8'
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  username: __token__
  password:
    secure: mkyQ/Vm1tNpBQNo0Bx71TSB8P0wVr+ew3QtcMfoYIaz84shBPiiV+E43OiqjFDxa1Brek41oInqznXVzCwnnPphOMfsiDItxDqhxOgpPQP3pJCj2/DNOi0x0Gby6uD0e85i2OUrkm3HH3ymtVNsjAU4WKTj95c3K2MvIm1TdAHyQkV1KRU9b7E9sRai9ZVzGIrBkPMlBeEqjwmM3iPm89od/qlxc8MV3goto5z/4r3uN7uhM8GRcAp+QGEuyTfgHvIfRoM9g1hQJx4A25mRq+F0mmYwk3POH36fvdAM5FgGOhedPH8lc/szTZHQRyZLa/89z7632ZrFyfrVr3SH0zUXMlqHAOhOz4D0VZpvFZNFeSD7l2qrJ4GsoXFlUjH0vCuzd8kFdlUh4A0u2TRsXe1kq9XB2GtfOwyCnwtEeaRBVcBxkBin/vNewv5a+CvdQEp/jR6czxS0kMaGrnIKbduTbdfhN4V2r190H8/haXbQqs/QiWjq9GH2JrK28HluCjkLFCx4OgOgR2ytx7T5/A7Do6bF2m/QC3oslqgM1u4pEAQxOaR0eN+VFWLoMWaFy+DZzX8JYo3Rmnv4gukCEciK/Pl0/uoodEh85CJvLh1mHIBijeWFdjQ+QSxK/PR3OS0DwBhTpLUFldUPWFbvFdjT3NmqO6zPKnfToTle98Og=
  edge: true
  on:
    branch: master
