language: python
dist: xenial
python:
- '3.8'
- '3.7'
- '3.6'
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  username: __token__
  password:
    secure: f7txmEjXWK9P3AEG+j2eCjIrBfDglJa/oZ1LmReA3ZGx8S4dhUweSOE+s9qPcCvDzX4gaUU8N0nPJBmE2+C0/hGGwkHYyLcqzDzhkJc6TNqMdFCN+fGAOKS35EgolKOcB3dZvO64wckE8fDO0FGJN6FwwOj1Nh5fC3oRBEDlpAZmQcTsrgjSqczT2wnzQ2bkAoJLHT6kdnFaPTPktKBQS14on1UkUaBrxq0fynNFwolCKOi2763yCTWqkZiu667YTYyrV3uWYYG7i5I9u9xd7FQWlsaHg7AqOnObQPGqNJ4LXWUOXrHla1WECDopPAt9w/78Vc7vmoUE+V1odab7AyBxm2xlcCJ6Kow7dQKRAjgrxMTwh/JDSs6piGG3aAlUadjooxfEWPjpRtOrtovMGNBwICclfSm5/+tmGNe5ThIGnW9D1j3FWfP2cdp1gJ1Cvh/EROzpLFEmBDZjQ+yW1r3bFC24MLP/FKLZfd8NTWYNKI9qEb80z3pFMn+vi4xtaTtu15IsJKMmatDXImadxIJ0HlM/Mr3Eyh6FCMKH6/b0iQFUTPzmT2VT8QugV7CtDLRZz5s1YgNs0E13pmImHxHYImCJOZRknNP9mm+FCJePmiQzVdrcvUuMY6VZ2vq+uknI9CWBc+qZjKUjXL9FajvhsLReq+0bf3xo573cia4=
  edge: true
