language: python
dist: xenial
python:
- '3.8'
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  username: __token__
  password:
    secure: oBhy8pICMHjp73Lf/389Nq1E30pbHMY8JUhPi+bsp5vhnJUN4poyPY26GJsZA/vVgkOEB/2nBB3zLNAGQ0RQFkAE5UdpCiL7V+8PgQLsmYDFgl+0R7iXuoBzJwWGpRMwP2qed2/0Oz2QX3nSCJX4j07FbFWp7LTkH/TRYVpRSMIsROdivBUwj+CtRtjg2Txdb5hAnwDJXj/idaLGpMrxx/SpF/YbfunIDTs0AdKGHqGkiXAt4fTZZaKTdLdQEPiL+f84OjEaZlRBlONnQ4yIi+KW8hNydTx41fqw31JcOm+08G1HfZeObeoLLFyOrgKCdChN0A7IO35Ih3KXbizdsmbACghLoUDq9pDWJRRtRDOHpRFQkbT3M85qEEcio5sO3dseqMYHy4tBDHzqK1BVaVI0+RTO/g45lJNt8Z5QLceV/tSDIQgH6aGKcsJNyWy+xXSOnIofWa9HFp8/kZ6jM/eEEZmI5TUPRo04kyzoVXRzkV0stO7sseh/I91HNW1WAM00OHQNPzh4vTRWtpQOhUmVS+AJ4uJeYLWeCCpOh1MgeA7uBM0KHyHqaUwEioed9l2w4rrH3Xnda3rX5P9X/fJwWsCy+jb041vIst/3stWStzpZ1CTJrD9hQ2uHN5xK6XLQVO8eqB5JYY7/GRlplyrt7KODpXPJUksHoesTTzQ=
  edge: true
  on:
    branch: master
